// <auto-generated />
using System;
using App_DataBaseEntity.DbContextEntity_SQL_Sever;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib_DataEntity.Migrations
{
    [DbContext(typeof(Trendyt_DbContext))]
    [Migration("20240508115134_create_table_tbAccount")]
    partial class create_table_tbAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbAccount", b =>
                {
                    b.Property<int>("id_Account")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Account"));

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_Create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("birthday_User")
                        .HasColumnType("datetime2");

                    b.Property<string>("email_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_Role")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_TypeAccount")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("image_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Ban")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("phone_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Account");

                    b.HasIndex("id_Role");

                    b.HasIndex("id_TypeAccount");

                    b.ToTable("tbAccount");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRole", b =>
                {
                    b.Property<Guid>("id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Role");

                    b.ToTable("tbRole");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRoleSchool", b =>
                {
                    b.Property<Guid>("id_RoleSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_RoleSchool");

                    b.ToTable("tbRoleSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbTypeAccount", b =>
                {
                    b.Property<Guid>("id_TypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_TypeAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_TypeAccount");

                    b.ToTable("tbTypeAccount");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbStyleBuoiHoc", b =>
                {
                    b.Property<int>("id_StyleBuoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_StyleBuoiHoc"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_StyleBuoiHoc");

                    b.ToTable("tbStyleBuoiHoc");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbTag", b =>
                {
                    b.Property<int>("id_Tag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Tag"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Tag");

                    b.ToTable("tbTag");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbAccount", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbRole", "tbRole")
                        .WithMany()
                        .HasForeignKey("id_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Models.Models_Table_CSDL.tbTypeAccount", "tbTypeAccount")
                        .WithMany()
                        .HasForeignKey("id_TypeAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbRole");

                    b.Navigation("tbTypeAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
