// <auto-generated />
using System;
using App_DataBaseEntity.DbContextEntity_SQL_Sever;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib_DataEntity.Migrations
{
    [DbContext(typeof(Trendyt_DbContext))]
    [Migration("20240125080139_add_table_tbTypeAccount")]
    partial class add_table_tbTypeAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRole", b =>
                {
                    b.Property<Guid>("id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Role");

                    b.ToTable("tbRole");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbTypeAccount", b =>
                {
                    b.Property<Guid>("id_TypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_TypeAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_TypeAccount");

                    b.ToTable("tbTypeAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
