// <auto-generated />
using System;
using App_DataBaseEntity.DbContextEntity_SQL_Sever;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib_DataEntity.Migrations
{
    [DbContext(typeof(Trendyt_DbContext))]
    [Migration("20240508114932_create_base_table")]
    partial class create_base_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRole", b =>
                {
                    b.Property<Guid>("id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Role");

                    b.ToTable("tbRole");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRoleSchool", b =>
                {
                    b.Property<Guid>("id_RoleSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_RoleSchool");

                    b.ToTable("tbRoleSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbTypeAccount", b =>
                {
                    b.Property<Guid>("id_TypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_TypeAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_TypeAccount");

                    b.ToTable("tbTypeAccount");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbStyleBuoiHoc", b =>
                {
                    b.Property<int>("id_StyleBuoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_StyleBuoiHoc"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_StyleBuoiHoc");

                    b.ToTable("tbStyleBuoiHoc");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbTag", b =>
                {
                    b.Property<int>("id_Tag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Tag"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Tag");

                    b.ToTable("tbTag");
                });
#pragma warning restore 612, 618
        }
    }
}
