// <auto-generated />
using System;
using App_DataBaseEntity.DbContextEntity_SQL_Sever;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib_DataEntity.Migrations
{
    [DbContext(typeof(Trendyt_DbContext))]
    [Migration("20240509113544_clear3")]
    partial class clear3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbAccount", b =>
                {
                    b.Property<int>("id_Account")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Account"));

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_Create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("birthday_User")
                        .HasColumnType("datetime2");

                    b.Property<string>("email_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_Role")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_TypeAccount")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("image_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Ban")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("phone_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("user_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Account");

                    b.HasIndex("id_Role");

                    b.HasIndex("id_TypeAccount");

                    b.HasIndex("user_Name")
                        .IsUnique()
                        .HasFilter("[user_Name] IS NOT NULL");

                    b.ToTable("tbAccount");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbClassSchool", b =>
                {
                    b.Property<int>("id_ClassSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_ClassSchool"));

                    b.Property<int>("id_KhoaSchool")
                        .HasColumnType("int");

                    b.Property<int>("id_Tag")
                        .HasColumnType("int");

                    b.Property<string>("name_ClassSchool")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_ClassSchool");

                    b.HasIndex("id_KhoaSchool");

                    b.HasIndex("id_Tag");

                    b.ToTable("tbClassSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbClassSchool_Menber", b =>
                {
                    b.Property<int>("id_MonHocClass_Student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_MonHocClass_Student"));

                    b.Property<int>("id_ClassSchool")
                        .HasColumnType("int");

                    b.Property<int>("id_MenberSchool")
                        .HasColumnType("int");

                    b.HasKey("id_MonHocClass_Student");

                    b.HasIndex("id_ClassSchool");

                    b.HasIndex("id_MenberSchool");

                    b.ToTable("tbClassSchool_Menber");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbKhoaSchool", b =>
                {
                    b.Property<int>("id_KhoaSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_KhoaSchool"));

                    b.Property<int>("id_School")
                        .HasColumnType("int");

                    b.Property<string>("ma_Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_KhoaSchool");

                    b.HasIndex("id_School");

                    b.ToTable("tbKhoaSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbMenberSchool", b =>
                {
                    b.Property<int>("id_MenberSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_MenberSchool"));

                    b.Property<float>("danhGiaTb")
                        .HasColumnType("real");

                    b.Property<int>("id_Account")
                        .HasColumnType("int");

                    b.Property<int>("id_KhoaSchool")
                        .HasColumnType("int");

                    b.Property<Guid>("id_RoleSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("id_School")
                        .HasColumnType("int");

                    b.Property<int>("id_Tag")
                        .HasColumnType("int");

                    b.HasKey("id_MenberSchool");

                    b.HasIndex("id_Account");

                    b.HasIndex("id_RoleSchool");

                    b.HasIndex("id_School");

                    b.HasIndex("id_Tag");

                    b.ToTable("tbMenberSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRole", b =>
                {
                    b.Property<Guid>("id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Role");

                    b.ToTable("tbRole");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbRoleSchool", b =>
                {
                    b.Property<Guid>("id_RoleSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_RoleSchool");

                    b.ToTable("tbRoleSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbSchool", b =>
                {
                    b.Property<int>("id_School")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_School"));

                    b.Property<string>("adderss_School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description_School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("evaluate_School")
                        .HasColumnType("real");

                    b.Property<int>("id_Account")
                        .HasColumnType("int");

                    b.Property<string>("name_School")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_School");

                    b.HasIndex("id_Account");

                    b.ToTable("tbSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbToken", b =>
                {
                    b.Property<Guid>("id_Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("access_Expire_Token")
                        .HasColumnType("datetime2");

                    b.Property<string>("access_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("browserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Account")
                        .HasColumnType("int");

                    b.Property<string>("ipv4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ipv6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Active")
                        .HasColumnType("bit");

                    b.Property<string>("key_refresh_Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("refresh_Expire_Token")
                        .HasColumnType("datetime2");

                    b.Property<string>("refresh_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("time_login")
                        .HasColumnType("datetime2");

                    b.HasKey("id_Token");

                    b.HasIndex("id_Account");

                    b.HasIndex("key_refresh_Token")
                        .IsUnique()
                        .HasFilter("[key_refresh_Token] IS NOT NULL");

                    b.ToTable("tbToken");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbTypeAccount", b =>
                {
                    b.Property<Guid>("id_TypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name_TypeAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_TypeAccount");

                    b.ToTable("tbTypeAccount");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbLichHoc", b =>
                {
                    b.Property<int>("id_LichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_LichHoc"));

                    b.Property<int>("id_MonHoc")
                        .HasColumnType("int");

                    b.Property<int>("id_StyleBuoiHoc")
                        .HasColumnType("int");

                    b.Property<string>("phonghoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("id_LichHoc");

                    b.HasIndex("id_MonHoc");

                    b.HasIndex("id_StyleBuoiHoc");

                    b.ToTable("tbLichHoc");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbMonHoc", b =>
                {
                    b.Property<int>("id_MonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_MonHoc"));

                    b.Property<int>("_SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("_SoBuoiNghi")
                        .HasColumnType("int");

                    b.Property<float>("_danhGiaTrungBinh")
                        .HasColumnType("real");

                    b.Property<int>("id_School")
                        .HasColumnType("int");

                    b.Property<int>("id_Tag")
                        .HasColumnType("int");

                    b.Property<string>("name_MonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("id_MonHoc");

                    b.HasIndex("id_School");

                    b.HasIndex("id_Tag");

                    b.ToTable("tbMonHoc");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbMonHocClass_Student", b =>
                {
                    b.Property<int>("id_MonHocClass_Student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_MonHocClass_Student"));

                    b.Property<int>("id_MenberSchool")
                        .HasColumnType("int");

                    b.Property<int>("id_MonHoc")
                        .HasColumnType("int");

                    b.HasKey("id_MonHocClass_Student");

                    b.HasIndex("id_MenberSchool");

                    b.HasIndex("id_MonHoc");

                    b.ToTable("tbMonHocClass_Student");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbStyleBuoiHoc", b =>
                {
                    b.Property<int>("id_StyleBuoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_StyleBuoiHoc"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_StyleBuoiHoc");

                    b.ToTable("tbStyleBuoiHoc");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbTag", b =>
                {
                    b.Property<int>("id_Tag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Tag"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Tag");

                    b.ToTable("tbTag");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbAccount", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbRole", "tbRole")
                        .WithMany()
                        .HasForeignKey("id_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Models.Models_Table_CSDL.tbTypeAccount", "tbTypeAccount")
                        .WithMany()
                        .HasForeignKey("id_TypeAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbRole");

                    b.Navigation("tbTypeAccount");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbClassSchool", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbKhoaSchool", "tbKhoaSchool")
                        .WithMany()
                        .HasForeignKey("id_KhoaSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Models.Models_Table_Entity.tbTag", "tbTag")
                        .WithMany()
                        .HasForeignKey("id_Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbKhoaSchool");

                    b.Navigation("tbTag");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbClassSchool_Menber", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbClassSchool", "tbClassSchool")
                        .WithMany()
                        .HasForeignKey("id_ClassSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Models.Models_Table_CSDL.tbMenberSchool", "tbMenberSchool")
                        .WithMany()
                        .HasForeignKey("id_MenberSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbClassSchool");

                    b.Navigation("tbMenberSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbKhoaSchool", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbSchool", "tbSchool")
                        .WithMany()
                        .HasForeignKey("id_School")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbSchool");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbMenberSchool", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbAccount", "tbAccount")
                        .WithMany()
                        .HasForeignKey("id_Account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Models.Models_Table_CSDL.tbRoleSchool", "tbRoleSchool")
                        .WithMany()
                        .HasForeignKey("id_RoleSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Models.Models_Table_CSDL.tbSchool", "tbSchool")
                        .WithMany()
                        .HasForeignKey("id_School")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Models.Models_Table_Entity.tbTag", "tbTag")
                        .WithMany()
                        .HasForeignKey("id_Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbAccount");

                    b.Navigation("tbRoleSchool");

                    b.Navigation("tbSchool");

                    b.Navigation("tbTag");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbSchool", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbAccount", "tbAccount")
                        .WithMany()
                        .HasForeignKey("id_Account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbAccount");
                });

            modelBuilder.Entity("App_Models.Models_Table_CSDL.tbToken", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbAccount", "tbAccount")
                        .WithMany()
                        .HasForeignKey("id_Account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbAccount");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbLichHoc", b =>
                {
                    b.HasOne("Lib_Models.Models_Table_Entity.tbMonHoc", "tbMonHoc")
                        .WithMany()
                        .HasForeignKey("id_MonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Models.Models_Table_Entity.tbStyleBuoiHoc", "tbStyleBuoiHoc")
                        .WithMany()
                        .HasForeignKey("id_StyleBuoiHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbMonHoc");

                    b.Navigation("tbStyleBuoiHoc");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbMonHoc", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbSchool", "tbSchool")
                        .WithMany()
                        .HasForeignKey("id_School")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Models.Models_Table_Entity.tbTag", "tbTag")
                        .WithMany()
                        .HasForeignKey("id_Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbSchool");

                    b.Navigation("tbTag");
                });

            modelBuilder.Entity("Lib_Models.Models_Table_Entity.tbMonHocClass_Student", b =>
                {
                    b.HasOne("App_Models.Models_Table_CSDL.tbMenberSchool", "tbMenberSchool")
                        .WithMany()
                        .HasForeignKey("id_MenberSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib_Models.Models_Table_Entity.tbMonHoc", "tbMonHoc")
                        .WithMany()
                        .HasForeignKey("id_MonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbMenberSchool");

                    b.Navigation("tbMonHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
